# Generated by Django 5.0.14 on 2026-03-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_customizeplan',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The plan tier this addon exclusively belongs to (e.g. Diamond)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_addons', to='app1.plan'),
        ),
    ]
